#ifndef PG_GENERIC_DATA_STRUCTURES_TEST_GENERIC_DICTIONARY_H
#define PG_GENERIC_DATA_STRUCTURES_TEST_GENERIC_DICTIONARY_H

void test_dict(void);

#endif      /*  PG_GENERIC_DATA_STRUCTURES_TEST_DICTIONARY_H  */

