#ifndef PG_GENERIC_DATA_STRUCTURES_TEST_STD_WRAPPERS_H
#define PG_GENERIC_DATA_STRUCTURES_TEST_STD_WRAPPERS_H

void test_std_wrappers(void);

#endif      /*  PG_GENERIC_DATA_STRUCTURES_TEST_STD_WRAPPERS_H  */

